# Generated by Django 4.0.4 on 2022-11-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_order_product_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
