# Generated by Django 4.0.4 on 2022-11-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
