# Generated by Django 4.0.4 on 2022-11-30 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0002_storeproduct_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproduct',
            name='tags',
        ),
    ]
